version: '3.9'

services:
  symshop:
    build: docker
    ports:
      - "9000:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - .:/var/www
    depends_on:
      - db
      - maildev
    environment:
      DATABASE_URL: "mysql://abdak:root@mysql-db:3306/symshop" # Utilisation du hostname
      MAILER_DSN: smtp://maildev:25

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symshop
      MYSQL_USER: abdak
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    hostname: mysql-db # Définition du hostname
    ports:
      - "3306:3306" # Optionnel, mais pratique pour l'accès depuis l'extérieur

  maildev:
    image: maildev/maildev
    ports:
      - "1080:80" # Port pour l'interface web
      - "1025:25" # Port SMTP

volumes:
  mysql_data:
